#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: xcom-client
main: net.peacefulcraft.xcom.client.XCOMClient
version: 0.0.1
api-version: 1.16
website: https://www.peacefulcraft.net/
depend: []
softdepend: []

commands:
  xcm-profile:
    description: XCOM Profile Debug Command
    permission-message:  Permission xcom.* is required to use this command
    usage: /<command> to use the example command.

permissions:
  xcom.*:
    description: Gives access to all xcom commands
